[package]
name = "yamux-low-mem"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.1", features = ["display"] }
derive_builder = "0.20"
futures = "0.3"
thiserror = "2.0"
log = "0.4"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["compat"] }
yamux = { version = "0.13.8" }
